[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[start]
cmd = 'php artisan storage:link && php artisan migrate --force && php artisan config:cache && php artisan view:cache && php -S 0.0.0.0:$PORT -t public'
